# Setup

baseURL = "http://anniesui.org/"
languageCode = "en-us"
title = "Welcome to Annie's Blog âœï¸"
theme = "etch"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true
ignoreErrors = ["error-missing-instagram-accesstoken"]
paginate = 10
paginate_path = "/posts/:num/"

[params]
  description = "musings of a pixie dream girl"
  copyright = "copyright Â© 2021 annie sui âœï¸ coded by yours truly ğŸ’–"
  dark = "auto"
  highlight = true
  google_fonts = [
    ["Fira Code", "400, 700"],
    ["Open Sans", "400, 400i, 700, 700i"],
    ["Nunito Sans", "300"],
    ["Nunito", "200, 300"]
  ]

  heading_font = "Fira Code"
  body_font = "Open Sans"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/"
    weight = 10

    [[menu.main]]
    identifier = "about"
    name = "about"
    title = "about"
    url = "/about/"
    weight = 20

[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  # Allows HTML in Markdown
  unsafe = true
